# Generated by Django 4.0.6 on 2022-07-25 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbase',
            name='address',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='userbase',
            name='city',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='userbase',
            name='planet',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='userbase',
            name='sector',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
