# Generated by Django 4.0.6 on 2022-07-19 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_rename_title_product_item_rename_author_product_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='type',
        ),
        migrations.AddField(
            model_name='product',
            name='short_note',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
